name: Deploy Deezcord Chat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # changed from ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install & Build
        run: |
          cd /home/deezcord/repos/CS323_FinalsPIT_Deezcord/client && npm install && npm run build
          cd ../server && npm install && npm run build
        
      - name: Restart App
        run: sudo systemctl restart deezcord_chat
